### ISSUE TITLE
release kar file

### ISSUE THREAD

**Issue by Hokwang** [sonatype-nexus-community/nexus-repository-conan#106]
Hello.

your readme.md said user can use nexus-repository-conan-0.0.6-bundle.kar.
But where is it? 

How about release this file?

And now there is 0.0.4 is latest in release tab.

Please keep your attention to this repo.

Thanks,

**Comment by bhamail** [comment]
Thanks for reporting this. I think it may be a result of a mistake in the CI config.

I think updating to the latest `circleci-maven-release-orb` and adding a custom override of the parameter: `mvn-release-prepare-command` to activate the 'kar' profile (`-PbuildKar`) should fix it.

Something like: 
`mvn-release-prepare-command: mvn --batch-mode release:prepare -DscmCommentPrefix="[skip ci] [maven-release-plugin] " -PbuildKar`

added here-ish: https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/master/.circleci/config.yml#L29

**Comment by aornatovskyy** [comment]
@Hokwang Thanks for posting an issue. Please be note that soon the plugin will be published and included inside the NXRM. So keep your attention with NXRM 3.22 release. This ticket will be closed just after NXRM 3.22 release.

**Comment by bhamail** [comment]
@Hokwang My apologies, the original fix I applied to include the .kar bundle in the release did not work. I've "really fixed" it this time, and verified the latest release does include the .kar bundle file when publishing to central.

Please be aware we are working on an issue that occurs when you try to use a newer .kar bundle for a format that Nexus also ships with (e.g. the format already exists in Nexus). Short-term, using one of the non-.kar approaches seems to work, but we're looking for a better solution.
