### ISSUE TITLE
Hosted Repository in Nexus 3.22+

### ISSUE THREAD

**Issue by Crypt0Marku5** [sonatype-nexus-community/nexus-repository-conan#118]
Hi, 

we've been using a hosted Conan repository for a while now, however, with the included plugin starting at version 3.22 this does not seem to be supported anymore.  
Is this not in scope anymore? Are there plans to add this functionality again in the future? 

Thanks & best regards

**Comment by aornatovskyy** [comment]
Hi @Crypt0Marku5  
You can try turn it on by using feature flag. 

1. Stop Nexus 3.22
2. Add property `sonatype-work/nexus3/etc/nexus.properties` -> **nexus.conan.hosted.enabled=true** 
3. Start Nexus 

**Important!** But be note that it is not officially supported yet, same deal as the community plugin. 

Regards

**Comment by igorudovika** [comment]
Hello @Crypt0Marku5 NXRM supports only Conan proxy one in 3.22 release.
You can add nexus.conan.hosted.enabled=true property into nexus.properties file and restart your NXRM. It will enable hosted one. But it is still not officially supported feature for now.

**Comment by Crypt0Marku5** [comment]
Ok, this was a combination of me not properly reading the readme and I think the same issue as in https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/113.  
We just updated to 3.22.1 and set the hosted.enabled flag, everything is working fine now.  

Thank you very much @igorudovika
