### ISSUE TITLE
conan search

### ISSUE THREAD

**Issue by doddi** [sonatype-nexus-community/nexus-repository-conan#13]
Implement the search endpoint https://github.com/conan-io/conan/blob/1afadb5cca9e1c688c7b37c69a0ff3c6a6dbe257/conans/server/rest/controllers/conan_controller.py#L130

**Comment by igorudovika** [comment]
Implemented the search endpoint for Conan proxy repository. Released in 1.0.2

**Comment by VenoMpie** [comment]
Still not fixed even in 1.0.3

ID | 260
-- | --
Name | nexus-repository-conan
Symbolic Name | org.sonatype.nexus.plugins.nexus-repository-conan
Version | 1.0.3
State | Active
Location | reference:file:system/org/sonatype/nexus/plugins/nexus-repository-conan/1.0.3/nexus-repository-conan-1.0.3.jar
Start Level | 200
Last Modified | 1590564744979

conan search -r test-nexus
ERROR: 404: Not Found. [Remote: test-nexus]

Tried
https://xxx/repository/conan-test/
https://xxx/repository/conan-test

Conan upload works well, conan install/search doesn't
A simple install from the remote works but as soon as something is required it fails

conan upload testpackage/1.6.135@test-nexus/stable -r test-nexus
Uploading to remote 'test-nexus':
Uploading testpackage/1.6.135@test-nexus/stable to remote 'test-nexus'
Uploaded conan_sources.tgz -> testpackage/1.6.135@test-nexus/stable [2.10k]
Uploaded conanfile.py -> testpackage/1.6.135@test-nexus/stable [1.56k]
Uploaded conanmanifest.txt -> testpackage/1.6.135@test-nexus/stable [0.29k]
Uploaded conan recipe 'testpackage/1.6.135@test-nexus/stable' to 'test-nexus': https://xxx/repository/test-nexus/

Is there someway that I should enable it or something?
