### ISSUE TITLE
Consider using an enum instead of a deserializer

### ISSUE THREAD

**Issue by doddi** [sonatype-nexus-community/nexus-repository-conan#17]
It might be worth considering using a simple enum rather than a deserialiser which is used to instantiate the correct ConanMatcher.
See discussion comments here https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/15#pullrequestreview-106088166

**Comment by igorudovika** [comment]
Outdated. Looks like code was redesigned few times.
