### ISSUE TITLE
conan upload with exports fails

### ISSUE THREAD

**Issue by gnarlie** [sonatype-nexus-community/nexus-repository-conan#21]
When uploading a package with an 'exports' field in the conanfile.py, the upload fails with:

```ERROR: 
Error uploading file: conan_export.tgz, ''
ERROR: Execute upload again to retry upload the failed files: conan_export.tgz. [Remote: coinbase]
```
This is needed only when there are files in addition to the conanfile & manifest required to build (e.g. a large patch set).

Not sure where to begin - for the present I'm eliminating the need for a patch file.

**Comment by doddi** [comment]
Although it is unlikely to make a difference have you tried with the latest 0.0.2 release?

Would it possible for you to attach an example that shows this error, it would help to debug the issueif that is possible?

**Comment by doddi** [comment]
@gnarlie it would be useful if you could open a separate ticket for the other issues with an example. It is extremely useful that you are providing these issues. Thanks a lot
