### ISSUE TITLE
Support /v1/ping API endpoint

### ISSUE THREAD

**Issue by DarkMorford** [sonatype-nexus-community/nexus-repository-conan#31]
* **What are you trying to do?**
Connect Conan 1.7.3 to a hosted repository on Nexus OSS 3.13.0-01 server

* **What feature or behavior is this required for?**
All Conan features

---

I've built and installed revision b79575f of the `nexus-repository-conan` plugin per the instructions in `README.md`. After creating a hosted Conan repository and adding it to my client machine, I tried to authenticate with `conan user` and got the following message:

    ERROR: Not implemented endpoint. [Remote: conan-local]

I also tried doing `conan search` and `conan upload` and got the same error every time. Wireshark shows that the client is trying to reach an endpoint at `/repository/conan-local/v1/ping` and the Nexus server is responding with a 404 status.

**Comment by DarkMorford** [comment]
After further investigation, it appears that the "correct" response to the `/v1/ping` endpoint (as demonstrated by the `conan_server` app that comes bundled with the client) is a 200 OK status with no body payload. It also sends along the following three HTTP headers:

    X-Conan-Server-Version: 1.7.4
    X-Conan-Server-Capabilities: complex_search
    X-Conan-Client-Version-Check: current

This was after updating my client to version 1.7.4; presumably the `Client-Version-Check` header would have been different using a 1.7.3 client.

**Comment by doddi** [comment]
@DarkMorford thanks for the ticket.
The ping endpoint (and search https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/13) is currently not implemented as yet. However, this should not stop you from performing an upload.
I also apologies that the readme is a little void of detail. Did you add the conan realm to you configuration?

If adding the realm to your configuration does not help you, could you provide the nexus.log of your attempts or a wireshark log I will see what I can help with.

As for the ping endpoint it would be awesome to have a community contributed PR ;)

**Comment by DarthHater** [comment]
Seconding @doddi , send us a PR for ping :)

**Comment by DarthHater** [comment]
@DarkMorford pop into the gitter we have linked in the README, I'll gladly help you out/guide you along the way!

As for where to start take a look at the routes here: https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/master/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy#L225

You'll need a matcher that matches the ping route.

You'll need to create the route like so: https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/master/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy#L155

By the looks of how @doddi has done things, you'll likely need to create a new AssetKind to represent that it's a ping request: https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/master/src/main/java/org/sonatype/repository/conan/internal/AssetKind.groovy#L23

From there you need a handler: https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/master/src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java#L101

Being this is a ping, you might be able to just reply with a 200 in the handler and call it a day, depending on what the ping endpoint does for Conan.

Hope this helps! Like I said pop into gitter and I'll totally help you out!

**Comment by doddi** [comment]
@DarkMorford I have tried issuing '```conan user ...```' and I dont see any ```/v1/ping``` in the messages.
Unfortunately I am only able to use version 1.7.3 of the conan client at the moment (I am using a mac), is it possible for you to try 1.7.3 or below to see if it is a recent introduction?

**Comment by doddi** [comment]
@DarkMorford having just tried an upload I can now see that a ```/v1/ping``` is now needed from newer versions of the client.
Thanks for reporting this

**Comment by doddi** [comment]
@DarkMorford I have created a PR for the support of ```/v1/ping```. If you cant wait you can try out the branch https://github.com/sonatype-nexus-community/nexus-repository-conan/tree/basic-ping-support and report back if that gets you passed uploading
