### ISSUE TITLE
Conan Proxy Repository does not work

### ISSUE THREAD

**Issue by MBollig** [sonatype-nexus-community/nexus-repository-conan#33]
I am using OSS 3.14.0-04 and  Nexus-Repository-Conan 0.0.3.

I created a 'Nexus Proxy repository' that refers to the conan center repository 'https://conan.bintray.com/'

`conan-center: https://nexus.mycompany.com/repository/conan-center/ [Verify SSL: False]`

Unfortuatelly I am not able to connect to the proxy due to the following error:

```
conan user myuser -p mypassword -r conan-center
ERROR: Not implemented endpoint. [Remote: conan-center]
```

Hosted repositories work as expected.

**Comment by doddi** [comment]
@MBollig have you added the Conan Bearer Token to the Realm configuration within your NXRM instance?

**Comment by MBollig** [comment]
Yes I have added the Conan Bearer Token to the Realm configuration.

**Comment by doddi** [comment]
@MBollig looks like the new clients have a ping endpoint, this PR adds the new endpoint https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/45
