### ISSUE TITLE
Upload of packages with shebang line in conanfile.py fails with strict content type validation on

### ISSUE THREAD

**Issue by ilyakrasnovsky** [sonatype-nexus-community/nexus-repository-conan#35]
First off, great work on this!

* **What are you trying to do?**

An example way to reproduce the issue, using Conan client 1.4.5 (also verified with >1.7), nexus-repository-conan 0.0.3, and Nexus OSS version 3.12.1-01. 

1. `$> conan install boost_algorithm/1.66.0@bincrafters/stable --remote=bincrafters-public-conan` (where bincrafters-public-conan is https://api.bintray.com/conan/bincrafters/public-conan, and the particular choice of `boost_algorithm` is important because the `conanfile.py` for it has a [shebang line](https://www.in-ulm.de/~mascheck/various/shebang/) on top, i.e. `#!/usr/bin/env python`)
2. `$> conan remote add conan-internal <MY-URL>` 
3. `$> conan user username -p password -r conan-internal`
4. `$> conan upload boost_algorithm/1.66.0@bincrafters/stable --remote=conan-internal --all`
5. Output:
```
Uploading boost_algorithm/1.66.0@bincrafters/stable to remote 'conan-internal'
Uploading conanmanifest.txt
[==================================================] 103B/103B
Uploading conanfile.py
[==================================================] 2.6KB/2.6KB
ERROR:
Error uploading file: conanfile.py, 'b'''
Uploading conan_export.tgz
[==================================================] 758B/758B
ERROR: Execute upload again to retry upload the failed files: conanfile.py. [Remote: conan-internal]
```
After placing a breakpoint [here](https://github.com/conan-io/conan/blob/399d2366533f2aeb4b1c4a63eeb83453bfcc8e2e/conans/client/rest/rest_client.py#L486) (for Conan client version 1.4.5, it moved in later versions but same issue), `response` was `HTTP 400 Bad Request: 'Detected content type [application/x-sh], but expected [text/x-python]: /v1/conans/bincrafters/boost_algorithm/1.66.0/stable/conanfile.py'`. This [unrelated SO post](https://stackoverflow.com/questions/50182301/deploying-a-jar-artifact-to-nexus-results-in-a-content-type-mismatch) tipped me off to disabling Strict Content Type Validation on the repository to work around this, and that worked, I was able to upload after unchecking this (see image below)
![strict_content_validation](https://user-images.githubusercontent.com/15662092/47376820-9f090200-d6c1-11e8-902a-7a73095d661c.PNG)

Given this behavior, I feel like the issue is rooted in the shebang line, but I don't understand enough about the content type validation feature to know whether it's a good idea to turn it off just for this. 

* **What feature or behavior is this required for?**

Any Conan package that has a shebang line won't be able to be uploaded without disabled strict content validation on the repository.

* **How could we solve this issue? (Not knowing is okay!)**

Obviously telling folks to uncheck Strict Content Type Validation seems to be a viable solution, but again, not sure if that's really the right answer. 

* **Anything else?**

**Comment by DarthHater** [comment]
I think you are right on, Tika is what we use for validation, and sometimes it gets funky. 

What I've done on other projects to kinda deal with Tika being a pain, is this:

https://github.com/sonatype-nexus-community/nexus-repository-chef/blob/ProxyPOC/src/main/java/org/sonatype/nexus/repository/chef/internal/ChefContentValidator.java#L58

You can create your own `ContentValidator` and do whatever you need to do in there to deal with this stuff. The upside of doing that is that you could limit the strictvalidation being turned off for only files you know you'll run into an issue on.

I could take a run at this, but I'm dropping this comment in here in case anyone else wants to :)

**Comment by ilyakrasnovsky** [comment]
Thanks @DarthHater ! It appears the relevant content validator in this repo is here:

https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/bc0dade13703f8e55817c20049cf3647a2f97335/src/main/java/org/sonatype/repository/conan/internal/security/ConanContentValidator.java#L45

I'll play around with changing this for shebang lines this next time I'm tasked in this area (because unchecking a box was easier up front) , at which point I can PR if you guys haven't already.

**Comment by DarthHater** [comment]
Yep! I wasn't sure if it had one or not, hence why I pointed at the other, but yeah that's the right place to start. Send a PR on over, we love getting contributions!

**Comment by doddi** [comment]
@ilyakrasnovsky apologies for taking so long to get around to taking a look at this issue. 
I have created a branch and raised a PR which should fix this problem (feel free to try out the branch to ensure the fix). It should be merged to master soon once I get some code reviews
