### ISSUE TITLE
Package install with update flag fails on no package found on remote

### ISSUE THREAD

**Issue by sciffer** [sonatype-nexus-community/nexus-repository-conan#38]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
update an install package using: conan install -u <pkg-name>
* **What feature or behavior is this required for?**
To update an already installed package(without version change).
* **How could we solve this issue? (Not knowing is okay!)**
Not sure yet, The issue needs to be pinned to the exact problem.
* **Anything else?**
Environment:
Nexus 3 OSS 3.14.0-04
nexus-repository-conan 0.0.4
conan client 1.1.0
Additional info:
When installing a package without the -u or the --update flag, everything works fine.
Afterwards if trying to install once again the same version with the --update or the -u, conan claims that the package could not be found on the remote (this issue does not exists with the basic conan server that you can get from the conan.io project).

**Comment by igorudovika** [comment]
Hello @sciffer 
Thanks for this info. We recently released NXRM 3.22 that contains Conan proxy repo out of the box. Installation with flag -u should work now fine from proxy one. Hosted repo unfortunately is still not officially supported
