### ISSUE TITLE
Error installing v0.0.6 with NXRM 3.16.2

### ISSUE THREAD

**Issue by JD1228** [sonatype-nexus-community/nexus-repository-conan#62]
* **What are you trying to do?**
Install the conan extension v0.0.6 on Nexus Repository v3.16.2-01 and use the proxy recipe.

* **What feature or behavior is this required for?**
Providing developer access to conan-center via NXRM.

* **How could we solve this issue? (Not knowing is okay!)**
Don't know the resolution.

* **Anything else?**
I attempted to integrate v0.0.4 with NXRM v3.16.2-01 initially, encountered problems, then found the discussion about the 'ping' API.  Removed (cleanly I hope) v0.0.4 and installed v0.0.6:  copied the .jar file, edited the nexus-pro-feature-3.16.2-01-features.xml file, restarted NXRM, created the proxy repo, added the Conan Bearer Token Realm to the Active list, added "browse" and "read" privileges to the appropriate role.  Configured conan client to use NXRM.  With v0.0.6 installed attempts to use the proxy repo return a 404 error.  In the server's nexus.log I found that when I save changes to the conan proxy repo the log shows "ERROR" messages on the "org.sonatype.repository.conan.internal.proxy.ConanProxyFacet - doValidate" entries.  Subsequent attempts to use the proxy repository result in "org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/<repo name>/v1/ping" messages followed by a "java.lang.IllegalStateException: Missing: org.sonatype.repository.conan.internal.AssetKind" stack traces.

**Comment by sciffer** [comment]
I just created Nexus repository 3.16.2 with the latest conan plugin 0.0.6 and everything works perfectly, not sure what went wrong for you but maybe you should try to compile the plugin in the docker image and pull it from there.
Make sure to replace all the 3.15.1 with 3.16.2 in the Dockerfile and you'll be good to go.

**Comment by gdraheim** [comment]
The respective AssetKind.class is actually getting compiled from AssetKind.groovy, and it is packaged into jar file is then packaged in the kar file. I can see the AssetKind.class in the Nexus3 deployment.

    unzip -v kar/nexus-repository-conan-0.0.6-bundle/org/sonatype/repository/nexus-repository-conan/0.0.6/nexus-repository-conan-0.0.6.jar | grep Asset
       7234  Defl:N     3092  57% 07-04-2019 10:30 9375611f  org/sonatype/repository/conan/internal/AssetKind.class

Nethertheless, I get the same error message in the nexus log and the respective conan proxy (to conan-center) does not work.

     + conan remote update conan-center https://pforgeipt.intra.airbusds.corp/nexus3/repository/conan-center False
     + conan install Component1/master@demo/testing
     Component1/master@demo/testing: Not found in local cache, looking in remotes...
     Component1/master@demo/testing: Trying with 'conan-center'...
     ERROR: 500: javax.servlet.ServletException: java.lang.IllegalStateException: Missing: 
     org.sonatype.repository.conan.internal.AssetKind. [Remote: conan-center]

**Comment by igorudovika** [comment]
Issue(response 404 error from Conan proxy) was fixed in Conan 1.x.x plug-in that available out of the box from NXRM 3.22.x release
