### ISSUE TITLE
Error generating conan bundle - Nexus 3.18

### ISSUE THREAD

**Issue by cristine** [sonatype-nexus-community/nexus-repository-conan#70]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Generate the conan bundle with Maven
* **What feature or behavior is this required for?**
I received an error because the commons-fileupload dependency  (version 1.3.2.SONATYPE) didn´t exist in a public maven repository:
![image](https://user-images.githubusercontent.com/1241795/65720926-5dc26480-e07f-11e9-8b94-9dfb4ce052cb.png)
How can I generate the conan bundle?
* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by bcg62** [comment]
Im also unable to build against 3.18

```
[ERROR] COMPILATION ERROR : 
[ERROR] /nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeGenerator.java:[31,21] 1. ERROR in /nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeGenerator.java (at line 31)
	public List<String> computeComponentPath(final Asset asset, final Component component) {
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method computeComponentPath(Asset, Component) of type ConanBrowseNodeGenerator must override or implement a supertype method

[ERROR] /nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeGenerator.java:[48,21] 2. ERROR in /nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeGenerator.java (at line 48)
	public List<String> computeAssetPath(final Asset asset, final Component component) {
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method computeAssetPath(Asset, Component) of type ConanBrowseNodeGenerator must override or implement a supertype method

[ERROR] /nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeGenerator.java:[56,14] 3. ERROR in /nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeGenerator.java (at line 56)
	return super.computeAssetPath(asset, component);
	             ^^^^^^^^^^^^^^^^
The method computeAssetPath(Asset, Component) is undefined for the type ComponentPathBrowseNodeGenerator```

**Comment by yasn77** [comment]
@bcg62 Looks like your problem is related to #66, @cristine has a different issue... That looks more like the maven repo they are using doesn't have a required dependency.

@cristine I would suggest to try using Maven central or add the missing dependency to your local Maven repo.

**Comment by cristine** [comment]
Ok but if you have this dependency with this version 1.3.2.SONATYPE could
you send to me? I didn’t find this dependency with this version in the
public maven central repository.

Em qui, 3 de out de 2019 às 07:09, Yasser Saleemi <notifications@github.com>
escreveu:

**Comment by yasn77** [comment]
@cristine You can find it in Sonatype repo...

https://repository.sonatype.org/service/local/repo_groups/forge/content/commons-fileupload/commons-fileupload/1.3.2.SONATYPE/commons-fileupload-1.3.2.SONATYPE.jar

**Comment by cristine** [comment]
Thanks!!! It is working now.
