### ISSUE TITLE
conan download 404

### ISSUE THREAD

**Issue by gdraheim** [sonatype-nexus-community/nexus-repository-conan#71]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
The "conan install <component>" works OK. Replacing it with "conan download <component>" FAILs.

* **What feature or behavior is this required for?**
The developer wants to find the latest version to package it up for delivery to a target system.

* **How could we solve this issue? (Not knowing is okay!)**
Implement the /search api - compare #13 

* **Anything else?**
Did "conan download" work at any time?

**Comment by gdraheim** [comment]
The server side nexus log file contains this - based on my own example with "conan download 'Component1/master@demo/testing' -r=nexus-conan"

    "GET /nexus3/repository/ipt-conan/v1/users/authenticate HTTP/1.1" 200 - 47 189 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"
    "GET /nexus3/repository/ipt-conan/v1/ping HTTP/1.1" 200 - 0 131 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"
    "GET /nexus3/repository/ipt-conan/v1/conans/Component1/master/demo/testing/download_urls HTTP/1.1" 200 - 453 143 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"
    "GET /nexus3/repository/ipt-conan/v1/conans/demo/Component1/master/testing/conanmanifest.txt HTTP/1.1" 200 - 276 113 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"
    "GET /nexus3/repository/ipt-conan/v1/conans/demo/Component1/master/testing/conanfile.py HTTP/1.1" 200 - 934 117 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"
    "GET /nexus3/repository/ipt-conan/v1/conans/Component1/master/demo/testing/download_urls HTTP/1.1" 200 - 453 127 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"
    "GET /nexus3/repository/ipt-conan/v1/conans/demo/Component1/master/testing/conan_sources.tgz HTTP/1.1" 200 - 449 111 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"
    "GET /nexus3/repository/ipt-conan/v1/conans/Component1/master/demo/testing/search HTTP/1.1" 404 - 2097 108 "Conan/1.19.1 (Python 2.7.5) python-requests/2.22.0"


As you can see, a "conan download" operation can find the same assets that a "conan install" will use but somewhere at the end it goes for the /search api.

The user will only see a 404

    + conan download Component1/master@demo/testing -r=nexus-conan
    Downloading conanmanifest.txt
    Downloading conanfile.py
    Downloading conan_sources.tgz
    Component1/master@demo/testing: Getting the complete package list from 'Component1/master@demo/testing#0'...
    ERROR: 404: Not Found. [Remote: nexus-conan]

**Comment by 1BE6-ankit** [comment]
@gdraheim Hello. The message 'Getting the complete package list' could probably mean that conan download requries a result from 'conan search' command. This repository contains an implementation for the search endpoints: https://github.com/1BE6-ankit/nexus-repository-conan/tree/hosted-search. If you are still looking for solutions, could you check if this works for you.

**Comment by igorudovika** [comment]
@gdraheim  NXRM 3.22 contains Conan proxy repo out of the box. We have implemented search endpoint for proxy one. Hosted one unfortunately still not officially supported.
