### ISSUE TITLE
Upload attempt failed

### ISSUE THREAD

**Issue by rwgs1976** [sonatype-nexus-community/nexus-repository-conan#72]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

I am trying to upload a projects and I am not succeeding.
I set up the nexus server correctly. I can authenticate myself but when I upload it rejects authentication.
How do I correct this problem.

![image](https://user-images.githubusercontent.com/17430765/67254390-1a2b0280-f453-11e9-9c90-371d8d83ddf1.png)

**Comment by doddi** [comment]
@rwgs1976 could you provide the nexus.log file from Nexus Repository Manager when attempting an upload, it might provide some insight into what is going wrong.

**Comment by peter-moran** [comment]
I am having the same issue. `conan user` seems to indicate that my password is correct -- if I intentionally use a wrong password, it tells me the password is wrong. With the correct password, it says nothing.

Here's what I'm running:
```
pmoran@pmoran-vb:~$ conan --version
Conan version 1.18.5
pmoran@pmoran-vb:~$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
morse: http://192.168.1.59:8082/artifactory/api/conan/conan-local [Verify SSL: True]
jpadsfsw: https://nexus.di2e.net/nexus3/repository/Private_JPADSFSW_Conan/ [Verify SSL: True]
pmoran@pmoran-vb:~$ conan user -r jpadsfsw peter.moran -p
Please enter a password for "peter.moran" account:
User of remote 'jpadsfsw' is already 'peter.moran'
pmoran@pmoran-vb:~$ conan upload opencv -r jpadsfsw
Are you sure you want to upload 'opencv/4.1.1@conan/stable' to 'jpadsfsw'? (yes/no): yes
Uploading to remote 'jpadsfsw':
Uploading opencv/4.1.1@conan/stable to remote 'jpadsfsw'
Please log in to "jpadsfsw" to perform this action. Execute "conan user" command.
Please enter a password for "peter.moran" account:
Please log in to "jpadsfsw" to perform this action. Execute "conan user" command.
Please enter a password for "peter.moran" account:
Please log in to "jpadsfsw" to perform this action. Execute "conan user" command.
Please enter a password for "peter.moran" account: You pressed Ctrl+C!
ERROR: Exiting with code: 3
```
[conan_trace_file.log](https://github.com/sonatype-nexus-community/nexus-repository-conan/files/3889880/conan_trace_file.log)

**Comment by rwgs1976** [comment]
Hi Peter,
 I fix this problem by activating conan realms as the figure below

![MicrosoftTeams-image](https://user-images.githubusercontent.com/17430765/69823985-47ed2f00-11e9-11ea-8180-73d3d203cdd3.png)
