### ISSUE TITLE
conan install with option --update doesn't work properly

### ISSUE THREAD

**Issue by sneik555** [sonatype-nexus-community/nexus-repository-conan#94]
Hi,

I called `conan install --update` when I had packages in my local cache.
I used local nexus with conan plugin and artifactory.

Logs:
[nexus_local.log](https://github.com/sonatype-nexus-community/nexus-repository-conan/files/4164912/nexus_local.log)
[artifactory_local.log](https://github.com/sonatype-nexus-community/nexus-repository-conan/files/4164913/artifactory_local.log)

On Artifactory only conanmanifest's was downloaded (as I excepted), because I had the same packages in my cache.
On nexus I see that conanfile's, conanmanifest's, conan_export's and conan_packages was downloaded too.

**Comment by igorudovika** [comment]
Fixed in NXRM 3.22 for Conan proxy repositories. Conan hosted one is still not officially supported
